# Generated by Django 4.1.3 on 2022-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_donator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=200),
        ),
    ]
