# Generated by Django 4.1.3 on 2022-12-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='donator',
        ),
        migrations.AddField(
            model_name='book',
            name='donor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='image2',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='image3',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='shipment_type',
            field=models.CharField(choices=[('R', 'Receiver'), ('D', 'Donor')], default='R', max_length=1),
        ),
    ]
