# Generated by Django 4.1.3 on 2022-12-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_donator_book_donor_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image3',
            field=models.TextField(blank=True),
        ),
    ]
