# Generated by Django 4.1.3 on 2022-12-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0002_alter_customuser_address_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='mass_fundraise',
            field=models.ManyToManyField(related_name='fundraised_books', to='books.book'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='obtained',
            field=models.ManyToManyField(related_name='obtained_books', to='books.book'),
        ),
    ]
